Enable k8s plugins for transform
konveyor/crane pull request #24
Opened 2021-08-09 19:16 UTC by eemcmullan

Enable k8s plugins from crane-lib for transform. 
#22

2021-08-09 21:24 UTC, sseago requested changes
This looks good, but I'd suggest a minor refactoring. Currently we have the concept of both binary and internal plugins (although we only have one example of the latter right now). GetBinaryPlugins pulls from the plugin dir. I think I'd rather preserve the functionality of GetBinaryPlugins as it exists today. Perhaps a new func `GetPlugins(dir string)` which starts with the kubernetes plugin (a list with one item in it), and then appends the results of `GetBinaryPlugins` to that list. Basically putting the new code from this PR into this new func, which calls the existing func. Otherwise people who weren't involved in this refactoring might be confused that `GetBinaryPlugins` returns both binary and internal plugins.

2021-08-09 21:26 UTC, sseago commented
Actually, with this refactoring, `GetBinaryPlugins` doesn't need to be an exported function, so forget what I said above. Leave it as-is, but just rename the exported func `GetPlugins` (and change the places where it's called).

2021-08-10 13:14 UTC, eemcmullan commented
Just updated `GetBinaryPlugins` to `GetPlugins`.

2021-08-10 13:23 UTC, sseago approved these changes

2021-08-10 18:17 UTC, shawn-hurley approved these changes
Looks good to me +1

thanks!

2021-08-10 18:17 UTC, shawn-hurley commented on cmd/transform/optionals/optionals.go
> +	PluginDir string
+1 thanks for fixing gofmt

2021-08-10 18:17 UTC, merged